# Generated by Django 4.2 on 2024-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
