# Generated by Django 4.2 on 2024-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0003_alter_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempavailability',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tempavailability',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
