# Generated by Django 4.2 on 2024-03-31 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meeting', '0004_alter_tempavailability_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invited',
            name='user',
        ),
    ]
