# Generated by Django 4.2 on 2024-04-10 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Meeting', '0005_remove_invited_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invited',
            name='invUser',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='invUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invited',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Meeting.calendar'),
        ),
    ]
